name: DevOps-GithubActions
run-name: ${{ github.actor }} pipeline demo avec Github Actions @
permissions:
  contents: write

on:
  [push]
  #[push, pull_request]
  #workflow_dispatch:

jobs:
  #Build job
  build:
    env:
      NODE_VERSION: 20
      COMMIT_MSG: "Build terminé avec succès!"

    runs-on: ubuntu-latest
    steps:
      - name: Ckeckout code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
          run: echo " $COMMIT_MSG "

  #Deploy job
  deploy:
    #Add a dependency to the build job
    needs: build
    #Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/browser
          commit_message: ${{ github.event.head_commit.message }}
